target 'AnalyticsExample' do
  platform :ios, '13.0'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnalyticsExample
  pod 'Firebase/Analytics'

  target 'AnalyticsExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnalyticsExampleUITests' do
    # Pods for testing
  end

end

target 'AnalyticsExampleMac' do
  platform :macos, '11.0'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnalyticsExampleMacSwiftUI
  pod 'Firebase/Analytics'

  target 'AnalyticsExampleMacTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


target 'AnalyticsExampleTV' do
  platform :tvos, '12.0'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnalyticsExampleTV
  pod 'Firebase/Analytics'

  target 'AnalyticsExampleTVTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

