# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

source "https://github.com/firebase/SpecsDev.git"
source "https://cdn.cocoapods.org/"

target 'AnalyticsExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnalyticsExample
  # pod 'Firebase/Analytics'
  pod 'FirebaseAnalytics', '8.7.0-swift-dep'

  target 'AnalyticsExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnalyticsExampleUITests' do
    # Pods for testing
  end

end
