# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'AnalyticsExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnalyticsExample
  pod 'Firebase/Analytics'

  target 'AnalyticsExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnalyticsExampleUITests' do
    # Pods for testing
  end

end
