source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
pod 'Firebase/AppInvites'

target 'AppInvitesExample'
target 'AppInvitesExampleSwift'
target 'AppInvitesExampleTests'
