source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'
# AnalyticsExample
platform :ios, '7.0'
pod 'Firebase/Core'
link_with 'AnalyticsExample', 'AnalyticsExampleSwift', 'AnalyticsExampleTests'
