# AnalyticsExample

use_frameworks!
platform :ios, '10.0'

target 'AnalyticsExample' do
  pod 'Firebase/Analytics'

  target 'AnalyticsExampleTests' do
    inherit! :search_paths
  end
end

target 'AnalyticsExampleSwift' do
  pod 'Firebase/Analytics'
end
