# AnalyticsExample

use_frameworks!
platform :ios, '13.0'

target 'AnalyticsExample' do
  pod 'FirebaseAnalytics'

  target 'AnalyticsExampleTests' do
    inherit! :search_paths
  end
end

target 'AnalyticsExampleSwift' do
  pod 'FirebaseAnalytics'
end
