platform :ios, '13.0'

target 'ABTestingExample' do
  use_frameworks!

  pod 'FirebaseAnalytics'
  pod 'FirebaseRemoteConfig'

  target 'ABTestingExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
