# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppDistributionExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppDistributionExample
  pod 'Firebase/Analytics'
  pod 'FirebaseAppDistribution', :git => 'https://github.com/firebase/firebase-ios-sdk.git'

  target 'AppDistributionExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppDistributionExampleUITests' do
    # Pods for testing
  end

end
