platform :ios, '10.0'

target 'ABTestingExample' do
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'

  # FirebaseInstanceID is needed to get a device token for debugging an experiment.
  pod 'FirebaseInstanceID', :configurations => ['Debug']

  target 'ABTestingExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
