platform :ios, '8.0'

target 'ABTestingExample' do
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'

  target 'ABTestingExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
