# CrashlyticsExample

source 'https://github.com/firebase/SpecsDev.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!
platform :ios, '10.0'

pod 'Firebase/Crashlytics'

target 'CrashlyticsExample'  do
end

target 'CrashlyticsExampleSwift' do
end
