# CrashlyticsExample
use_frameworks!
platform :ios, '8.0'

pod 'Firebase/Analytics'
pod 'FirebaseCrashlytics', :podspec => 'https://storage.googleapis.com/firebase-preview-drop/ios/crashlytics-eap/0.0.9/FirebaseCrashlyticsEAP.podspec'

target 'CrashlyticsExample'  do
end

target 'CrashlyticsExampleSwift' do
end
