use_frameworks!
platform :ios, '10.0'

pod 'Firebase/Analytics'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'

target 'AdMobExample' do

  target 'AdMobExampleTests' do
    inherit! :search_paths
  end
end

target 'AdMobExampleSwift' do

  target 'AdMobExampleSwiftTests' do
    inherit! :search_paths
  end
end
