source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'Firebase/AdMob'

target 'AdMobExample' do
end
target 'AdMobExampleSwift' do
end
target 'AdMobExampleTests' do
end
target 'AdMobExampleSwiftTests' do
end