source 'https://cpdc-eap.googlesource.com/firebase-ml.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

pod 'Firebase/Core'
pod 'FirebaseMLCommon', '0.1.48'
pod 'FirebaseMLModelInterpreter', '0.1.48'

target 'MLModelInterpreterExample' do
end

target 'MLModelInterpreterExampleObjC' do
end
