# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Swifty Auth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swifty Auth
  ## Firebase 🔥 Pods
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  
  ### For Email Link/Passwordless Auth
  pod 'Firebase/DynamicLinks'

  ## Pod for Sign in with Google
  pod 'GoogleSignIn'

  ## Pod for Sign in with Facebook
  pod 'FBSDKLoginKit'

  target 'Swifty AuthTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swifty AuthUITests' do
    # Pods for testing
  end

end
