source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

# [START customauth_pods]
pod 'Firebase/Core'
pod 'FirebaseAuth'
# [END customauth_pods]
pod 'FirebaseDatabase'

link_with 'CustomAuth', 'CustomAuthSwift', 'CustomAuthTests'
