# PerformanceExample
use_frameworks!
platform :ios, '8.0'

pod 'Firebase/Core'
pod 'Firebase/Performance'

target 'PerformanceExample' do
end
target 'PerformanceExampleSwift' do
end
target 'PerformanceExampleTests' do
end
