# PerformanceExample
use_frameworks!
platform :ios, '10.0'

pod 'Firebase/Analytics'
pod 'Firebase/Performance'

target 'PerformanceExample' do
end
target 'PerformanceExampleSwift' do
end
target 'PerformanceExampleTests' do
end
