# PerformanceExample
use_frameworks!
platform :ios, '10.0'

pod 'FirebaseAnalytics'
pod 'FirebasePerformance'

target 'PerformanceExample' do
end
target 'PerformanceExampleSwift' do
end
target 'PerformanceExampleTests' do
end
