platform :ios, '9.0'

# Replace both pods by pod 'Firebase/Installations' once FirebaseInstallations has released
pod 'FirebaseInstallations', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'mm/fis-integration-master'
pod 'Firebase/CoreOnly'

target 'InstallationsExample' do
  use_frameworks!
end

target 'InstallationsExampleSwift' do
  use_frameworks!
end
