# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'PasswordlessSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PasswordlessSwiftUI
  pod 'Firebase/Auth'
  pod 'Firebase/DynamicLinks'

  target 'PasswordlessSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PasswordlessSwiftUIUITests' do
    # Pods for testing
  end

end
