# DatabaseExample
source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'Firebase/Core'
pod 'FirebaseDatabase'

# If using CocoaPods 1.0.0+, use the new target syntax.
# target 'DatabaseExample'
# target 'DatabaseExampleSwift'
# target 'DatabaseExampleTests'

# and delete the link_with command.
link_with 'DatabaseExample', 'DatabaseExampleSwift', 'DatabaseExampleTests'