# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'sso://cpdc-internal/spec'
source 'https://github.com/CocoaPods/Specs.git'

target 'MLKitExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # [START base_dependencies]
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  # [END base_dependencies]
  pod 'Firebase/MLVisionBarcodeModel'
  pod 'Firebase/MLVisionFaceModel'
  pod 'Firebase/MLVisionLabelModel'
  pod 'Firebase/MLVisionTextModel'
  pod 'Firebase/MLModelInterpreter'

end
