# Uncomment the next line to define a global platform for your project

target 'PerformanceExample (iOS)' do
  platform :ios, '14.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PerformanceExample (iOS)
  pod 'Firebase'
  pod 'FirebasePerformance'

end

target 'Tests_iOS' do
  platform :ios, '14.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PerformanceExample (iOS)
  pod 'Firebase'
  pod 'FirebasePerformance'

end

target 'PerformanceExample (tvOS)' do
  platform :tvos, '14.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PerformanceExample (tvOS)
  pod 'Firebase'
  pod 'FirebasePerformance'

end
