use_frameworks!

pod 'Firebase'
pod 'FirebasePerformance'
pod 'FirebaseStorage'

target 'PerformanceExample (iOS)' do
  target 'Tests_iOS' do
    inherit! :search_paths
  end
end

target 'PerformanceExample (tvOS)' do
  target 'Tests_tvOS' do
    inherit! :search_paths
  end
end
