# CrashlyticsExample
use_frameworks!
platform :ios, '13.0'

target 'CrashlyticsExample'  do
  pod 'FirebaseCrashlytics'
  pod 'ReachabilitySwift'
end

target 'CrashlyticsExampleSwift' do
  pod 'FirebaseCrashlytics'
  pod 'ReachabilitySwift'
end
