# StorageExample

use_frameworks!
platform :ios, '13.0'

pod 'FirebaseAuth'
pod 'FirebaseStorage'

target 'StorageExample' do
end
target 'StorageExampleSwift' do
end
target 'StorageExampleTests' do
end
