# StorageExample

use_frameworks!
platform :ios, '10.0'

pod 'FirebaseAuth'
pod 'FirebaseStorage'

target 'StorageExample' do
end
target 'StorageExampleSwift' do
  pod 'FirebaseStorageSwift', "> 7.0-beta"
end
target 'StorageExampleTests' do
end
