# StorageExample

use_frameworks!
platform :ios, '8.0'

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Storage'

target 'StorageExample' do
end
target 'StorageExampleSwift' do
end
target 'StorageExampleTests' do
end
