# StorageExample

use_frameworks!
platform :ios, '10.0'

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Storage'

target 'StorageExample' do
end
target 'StorageExampleSwift' do
  pod 'FirebaseStorageSwift', "~> 7.0-beta"
end
target 'StorageExampleTests' do
end
