# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ConfigExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConfigExample
  pod 'FirebaseRemoteConfig', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'realtime-rc-merge'
  pod 'FirebaseRemoteConfigSwift', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'realtime-rc-merge'
  pod 'FirebaseAnalytics'

  target 'ConfigExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConfigExampleUITests' do
    # Pods for testing
  end

end
