# Firebase Cloud Messaging (FCM)

use_frameworks!
platform :ios, '8.0'

pod 'Firebase/Analytics'
pod 'Firebase/Messaging'

pod 'FirebaseInstanceID', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'mm/fis-integration-master'
pod 'FirebaseInstallations', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'mm/fis-integration-master'

target 'MessagingExample' do
end
target 'MessagingExampleSwift' do
end
target 'MessagingExampleTests' do
end
