# Firebase Cloud Messaging (FCM)

use_frameworks!
platform :ios, '11.0'

def firebase_pods
  pod 'FirebaseAnalytics'
  pod 'FirebaseMessaging'
end 

target 'MessagingExample' do
  firebase_pods
end
target 'MessagingExampleSwift' do
  firebase_pods
end

target 'MessagingExampleTests' do
end
