# CrashReportingExample
use_frameworks!
platform :ios, '8.0'
pod 'Firebase/Core'
pod 'Firebase/Crash'

target 'CrashReportingExample'  do
end
target 'CrashReportingExampleSwift' do
end
target 'CrashReportingExampleTests' do
end
