# DynamicLinksExample
source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
# [START pod_ddl]
pod 'Firebase/DurableDeepLink'
# [END pod_ddl]

target 'DynamicLinksExample' do
end
target 'DynamicLinksExampleSwift' do
end