# DynamicLinksExample

use_frameworks!
platform :ios, '10.0'

# [START pod_ddl]
pod 'Firebase/Analytics'
pod 'Firebase/DynamicLinks'
# [END pod_ddl]

target 'DynamicLinksExample' do
end
target 'DynamicLinksExampleSwift' do
end
target 'DynamicLinksExampleTests' do
end
