platform :ios, '9.0'

use_frameworks!

pod 'Firebase/MLNLTranslate'
pod 'Firebase/Analytics'

target 'TranslateExample' do
  target 'TranslateExampleTests' do
    inherit! :search_paths
  end
end

target 'TranslateExampleObjC' do
  target 'TranslateExampleObjCTests' do
    inherit! :search_paths
  end
end

target 'TranslateExampleUITests' do
end
