platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'FirebaseMLNLTranslate', '0.1.48'
pod 'FirebaseMLNaturalLanguage', '0.1.48'
pod 'FirebaseMLCommon', '0.1.48'

target 'TranslateExample' do
  target 'TranslateExampleTests' do
    inherit! :search_paths
  end
end

target 'TranslateExampleObjC' do
  target 'TranslateExampleObjCTests' do
    inherit! :search_paths
  end
end

