platform :ios, '13.0'

target 'FirestoreExample' do
  use_frameworks!

  pod 'FirebaseAuth'
  pod 'FirebaseUI/Auth', '~> 12.0'
  pod 'FirebaseUI/Email', '~> 12.0'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift', "> 7.0-beta"
  pod 'SDWebImage'

  target 'FirestoreExampleTests' do
    inherit! :search_paths
  end
end

target 'FirestoreSwiftUIExample' do
  use_frameworks!

  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift', "> 7.0-beta"
  pod 'SDWebImageSwiftUI'
end
