platform :ios, '8.0'

target 'FirestoreExample' do
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth', '~> 5.0'
  pod 'FirebaseUI/Google', '~> 5.0'
  pod 'Firebase/Firestore'
  pod 'SDWebImage'
  pod 'FirebaseFirestoreSwift', :path => '/Users/paulbeusterien/gh/firebase-ios-sdk/'

  target 'FirestoreExampleTests' do
    inherit! :search_paths
  end
end
