platform :ios, '9.0'
use_frameworks!

# [START base_dependencies]
pod 'Firebase/Core'
pod 'Firebase/MLVision'
# [END base_dependencies]
pod 'Firebase/MLVisionAutoML'
pod 'Firebase/MLVisionObjectDetection'
pod 'Firebase/MLVisionBarcodeModel'
pod 'Firebase/MLVisionFaceModel'
pod 'Firebase/MLVisionLabelModel'
pod 'Firebase/MLVisionTextModel'
pod 'FirebaseMLVisionObjectDetection'

target 'MLVisionExample' do
end

target 'MLVisionExampleObjc' do
end

