platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# [START base_dependencies]
pod 'Firebase/Core'
pod 'Firebase/MLVision'
# [END base_dependencies]
pod 'Firebase/MLVisionBarcodeModel'
pod 'Firebase/MLVisionFaceModel'
pod 'Firebase/MLVisionLabelModel'
pod 'Firebase/MLVisionTextModel'

target 'MLVisionExample' do
end

target 'MLVisionExampleObjc' do
end
