# FunctionsExample
#source 'sso://cpdc-internal/spec.git'
#source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '8.0'

pod 'Firebase/Core'
# [START smartreply_pod]
#pod 'FirebaseMLCommon', '0.1.17-beta4'
#pod 'MLText', '0.1.17-beta4'
# [END smartreply_pod]

pod 'MaterialComponents/Buttons'
pod 'MaterialComponents/Collections'
pod 'MaterialComponents/TextFields'

target 'SmartReplyExample' do
end
target 'SmartReplyExampleSwift' do
end
