# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

use_frameworks!

target 'InAppMessagingExample' do
  pod 'Firebase/Analytics'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/DynamicLinks'

  target 'InAppMessagingExampleTests' do
  end

  target 'InAppMessagingExampleUITests' do
  end
end

target 'InAppMessagingExampleSwift' do
  pod 'Firebase/Analytics'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/DynamicLinks'

  target 'InAppMessagingExampleSwiftTests' do
  end

  target 'InAppMessagingExampleSwiftUITests' do
  end
end
