# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

use_frameworks!

target 'InAppMessagingExample' do
  pod 'FirebaseAnalytics'
  pod 'FirebaseInAppMessaging', "> 8.11-beta"

  target 'InAppMessagingExampleTests' do
  end

  target 'InAppMessagingExampleUITests' do
  end
end

target 'InAppMessagingExampleSwift' do
  pod 'FirebaseAnalytics'
  pod 'FirebaseInAppMessaging', "> 8.11-beta"

  target 'InAppMessagingExampleSwiftTests' do
  end

  target 'InAppMessagingExampleSwiftUITests' do
  end
end
