# CrashReporter
source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
pod 'Firebase/CrashReporting'

target 'CrashReporter'
target 'CrashReporterSwift'
target 'CrashReporterTests'
