# CrashReporter
source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '7.0'
pod 'Firebase/Crash'

target 'CrashReporter'  do
end
target 'CrashReporterSwift' do
end
target 'CrashReporterTests' do
end
