# Note: CocoaPods version 1.0.0.beta.* or later is required for this Podfile.
#       If on an older version use "gem install cocoapods --pre" to update to
#       beta.

# CrashReporter
source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
pod 'Firebase/CrashReporting'

# If using CocoaPods 1.0.0+, use the new target syntax.
# target 'CrashReporter'
# target 'CrashReporterSwift'
# target 'CrashReporterTests'

# and delete the link_with command.
link_with 'CrashReporter', 'CrashReporterSwift', 'CrashReporterTests'
