# DurableLinksExample

# TODO (ulukaya): Remove EAP before after internal hackathon.
source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
pod 'Firebase/DurableDeepLink'

target 'DurableLinksExample'
target 'DurableLinksExampleSwift'
target 'DurableLinksExampleTests'
