#TODO: Delete next two lines on merging back to master.
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

# FunctionsExample

use_frameworks!
platform :ios, '10.0'

pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseUI/Auth', '~> 12.0'
pod 'FirebaseUI/Google', '~> 12.0'
# [START functions_pod]
pod 'FirebaseFunctions'
# [END functions_pod]

pod 'MaterialComponents/Buttons'
pod 'MaterialComponents/Collections'
pod 'MaterialComponents/TextFields'

target 'FunctionsExample' do
end
target 'FunctionsExampleSwift' do
end
