# FunctionsExample

use_frameworks!
platform :ios, '13.0'

pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseUI/Auth', '~> 14.0'
pod 'FirebaseUI/Google', '~> 14.0'
# [START functions_pod]
pod 'FirebaseFunctions'
# [END functions_pod]

pod 'MaterialComponents/Buttons'
pod 'MaterialComponents/Collections'
pod 'MaterialComponents/TextFields'

target 'FunctionsExample' do
end
target 'FunctionsExampleSwift' do
end
