# UserManagementExample

source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'Firebase/Core'
pod 'FirebaseAuth'
pod 'FirebaseAuthUI'
pod 'FirebaseAuthProviderGoogle'
pod 'FirebaseAuthProviderFacebook'

target 'UserManagementExample'
target 'UserManagementExampleSwift'
target 'UserManagementExampleTests'
