# UserManagementExample

source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'Firebase/Auth'
pod 'Firebase/AuthUI'
pod 'Firebase/GoogleAuthProvider'
pod 'Firebase/FacebookAuthProvider'

target 'UserManagementExample'
target 'UserManagementExampleSwift'
target 'UserManagementExampleTests'
