### Remove this when it goes to GA ###
source 'sso://cpdc-eap/spec.git'
source 'https://github.com/CocoaPods/Specs.git'
## End remove ###
# GcmExample
platform :ios, '7.0'
link_with 'GcmExample', 'GcmExampleSwift'
pod 'Firebase/CloudMessaging'
