### Remove this when it goes to GA ###
source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'
## End remove ###
# GcmExample
platform :ios, '7.0'
target 'GcmExample'
target 'GcmExampleSwift'
pod 'Firebase/CloudMessaging'
