### Remove this when it goes to GA ###
source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'
## End remove ###
# GcmExample
platform :ios, '7.0'

pod 'Firebase/CloudMessaging'

# If using CocoaPods 1.0.0+, use the new target syntax.
# target 'GcmExample'
# target 'GcmExampleSwift'

# and delete the link_with command.
link_with 'GcmExample', 'GcmExampleSwift'

