platform :ios, '9.0'

source 'sso://cpdc-test/firebase-ml'
source 'sso://cpdc-test/spec'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
pod 'Firebase/Core'
pod 'FirebaseMLNLLanguageID'

target 'LanguageIDExample' do
end
target 'LanguageIDExampleObjC' do
end
