name: xcodetest

on: [push]

jobs:

  build:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: CocoaPod Install
        run: |
          cd ./config/
          pwd
          pod install
      #- name: Testing....
      # run: ls /Applications | grep Xcode
      - name: Force xcode 11
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      - name: Add GoogleService-Info
        env:
          google_service_info: ${{ secrets.configGoogleServiceInfo }}
        run: |
          echo "$google_service_info" > ./GoogleService-Info.plist
          ruby GHA_testing_workflow/add_files_to_project.rb --files=./GoogleService-Info.plist --extras=add_reversed_client_id --project=./config/ConfigExample.xcodeproj
      - name: iPhone 11 Test
        env: # Or as an environment variable 
          super_secret: ${{ secrets.FIREGSignInInfo }}
        run: |
          echo "$super_secret"> ./TestUtils/FIREGSignInInfo.h
          cd ./config/
          pwd
          xcodebuild -workspace *.xcworkspace -list
          echo --------------------------------------------
          xcodebuild test -scheme ConfigExample -workspace ConfigExample.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3'
