# AuthenticationExample

source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
# [START auth_pod]
pod 'Firebase/Auth'
# [END auth_pod]
pod 'FirebaseAuthUI'
pod 'Firebase/SignIn'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'TwitterKit'

target 'AuthenticationExample'
target 'AuthenticationExampleSwift'
target 'AuthenticationExampleTests'
