# AuthenticationExample

source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'Firebase/Auth'
pod 'FirebaseAuthUI'
pod 'FirebaseGoogleAuthUI'
pod 'FirebaseFacebookAuthUI'

target 'AuthenticationExample'
target 'AuthenticationExampleSwift'
target 'AuthenticationExampleTests'
