# AuthenticationExample

source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
# [START auth_pod]
pod 'Firebase/Auth'
# [END auth_pod]
pod 'FirebaseAuthUI'
pod 'FirebaseGoogleAuthUI'
pod 'FirebaseFacebookAuthUI'

pod 'TwitterKit'

# If using CocoaPods 1.0.0+, use the new target syntax.
# target 'AuthenticationExample'
# target 'AuthenticationExampleSwift'
# target 'AuthenticationExampleTests'

# and delete the link_with command.
link_with 'AuthenticationExample', 'AuthenticationExampleSwift', 'AuthenticationExampleTests'